var template="";
template += "<!--to convert go here :";
template += "http:\/\/www.accessify.com\/tools-and-wizards\/developer-tools\/html-javascript-convertor\/";
template += "-->";
template += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
template += "<div align=\"center\" style=\"background-color: white\">";
template += "    <div class=\"container\">";
template += "        <div class=\"row clearfix\">";
template += "            <div class=\"col-md-12 column\">";
template += "                <b>HPI Encoder ver 1.0<\/b>";
template += "            <\/div>";
template += "        <\/div>";
template += "        <div class=\"row clearfix\" ng-hide=\"isInputFieldsAreValid\">";
template += "            <div class=\"col-md-12 column\">";
template += "                WARNING : the input fields was change since the last update. Pls contact Mike to fix this. You know";
template += "                where you can find me.";
template += "            <\/div>";
template += "        <\/div>";
template += "        <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
template += "            <div class=\"col-md-12 column\">";
template += "                <div class=\"panel panel-default\">";
template += "                    <div class=\"panel-heading\">";
template += "                        <h3 class=\"panel-title\">";
template += "                            Step 1 : Input the CSV to parse";
template += "                        <\/h3>";
template += "                    <\/div>";
template += "                    <div class=\"panel-body\">";
template += "                        <form role=\"form\">";
template += "                            <div class=\"form-group\">";
template += "                                <label for=\"csvText\">Paste CSV content here<\/label>";
template += "                                <textarea class=\"form-control\" id=\"csvText\" ng-model=\"csvContent\"><\/textarea>";
template += "                            <\/div>";
template += "                            <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">Parse<\/button>";
template += "                        <\/form>";
template += "                    <\/div>";
template += "                <\/div>";
template += "            <\/div>";
template += "        <\/div>";
template += "        <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
template += "            <div class=\"col-md-12 column\">";
template += "                <div class=\"panel panel-default\">";
template += "                    <div class=\"panel-heading\">";
template += "                        <h3 class=\"panel-title\">";
template += "                            Step 2 : Input user information";
template += "                        <\/h3>";
template += "                    <\/div>";
template += "                    <div class=\"panel-body\">";
template += "                        <form role=\"form\">";
template += "                            <div class=\"form-group\" ng-hide=\"true\">";
template += "                                <label>New Entry Or Re-Entry<\/label>";
template += "                                <select ng-model=\"entry\" class=\"form-control\"";
template += "                                        ng-options=\"entry for entry in entries\"><\/select>";
template += "                            <\/div>";
template += "                            <div class=\"form-group\" ng-show=\"entry == 'new entry'\">";
template += "                                <label for=\"uplineUserCode\">Your Upline User Code<\/label>";
template += "                                <input type=\"text\" id=\"uplineUserCode\" class=\"form-control\"";
template += "                                       placeholder=\"Your Upline User Code\" ng-model=\"uplineUserCode\"\/>";
template += "                            <\/div>";
template += "                            <div class=\"form-group\">";
template += "                                <label for=\"firstName\">First Name<\/label>";
template += "                                <input type=\"text\" id=\"firstName\" class=\"form-control\" placeholder=\"First Name\"";
template += "                                       ng-model=\"firstName\"\/>";
template += "                            <\/div>";
template += "                            <div class=\"form-group\">";
template += "                                <label for=\"middleName\">Middle Name<\/label>";
template += "                                <input type=\"text\" id=\"middleName\" class=\"form-control\" placeholder=\"Middle Name\"";
template += "                                       ng-model=\"middleName\"\/>";
template += "                            <\/div>";
template += "                            <div class=\"form-group\">";
template += "                                <label for=\"lastName\">Last Name<\/label>";
template += "                                <input type=\"text\" id=\"lastName\" class=\"form-control\" placeholder=\"Last Name\"";
template += "                                       ng-model=\"lastName\"\/>";
template += "                            <\/div>";
template += "                            <div class=\"form-group\">";
template += "                                <label for=\"userPassword\">User Password<\/label>";
template += "                                <input type=\"text\" id=\"userPassword\" class=\"form-control\" placeholder=\"User Password\"";
template += "                                       ng-model=\"password\"\/>";
template += "                            <\/div>";
template += "                        <\/form>";
template += "                    <\/div>";
template += "                <\/div>";
template += "            <\/div>";
template += "        <\/div>";
template += "        <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
template += "            <div class=\"col-md-12 column\">";
template += "                <div class=\"panel panel-default\">";
template += "                    <div class=\"panel-heading\">";
template += "                        <h3 class=\"panel-title\">";
template += "                            Step 3 : Correct the fields below and click Encode.";
template += "                        <\/h3>";
template += "                    <\/div>";
template += "                    <div>";
template += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Encode()\" ng-disabled=\"!isDone\">Encode";
template += "                            All";
template += "                        <\/button>";
template += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"StopEncoding()\">Stop";
template += "                        <\/button>";
template += "                    <\/div>";
template += "";
template += "                    <div class=\"panel-body\">";
template += "                        <table class=\"table\">";
template += "                            <thead>";
template += "                            <tr>";
template += "                                <th>";
template += "                                    #";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    User Code";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    Referred By";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    Activation Code";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    Status";
template += "                                <\/th>";
template += "                                <th>";
template += "                                        <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
template += "                                               ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Was Encoded";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    <input type=\"checkbox\" ng-model=\"enableEncodeOneItem\"";
template += "                                                  alt=\"Enable Encode One By One. By default this is disable to prevent accident.\"\/>";
template += "                                    Action";
template += "                                <\/th>";
template += "                            <\/tr>";
template += "                            <\/thead>";
template += "                            <tbody>";
template += "                            <tr ng-repeat=\"account in accounts\">";
template += "                                <th>";
template += "                                    {{account.Index}}";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    <input type=\"input\" ng-model=\"account.UserCode\"\/>";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    <input type=\"input\" ng-model=\"account.ReferredBy\"\/>";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    <input type=\"input\" ng-model=\"account.ActivationCode\"";
template += "                                           ng-change=\"ActivationCodeChange({{account.Index}})\"\/>";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    {{account.Status}}";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    <input type=\"checkbox\" ng-model=\"account.WasEncoded\"\/>";
template += "                                <\/th>";
template += "                                <th>";
template += "                                    <button ng-click=\"EncodeOneItem(account.Index)\" ng-disabled=\"!isDone || !enableEncodeOneItem\">";
template += "                                        Encode";
template += "                                    <\/button>";
template += "                                <\/th>";
template += "                            <\/tr>";
template += "                            <\/tbody>";
template += "                        <\/table>";
template += "                        <button type=\"button\" ng-csv=\"getArrayForCsv()\" filename=\"encoded.csv\"";
template += "                                csv-header=\"['User Code', 'Referred By', 'Activation Code']\">Export";
template += "                        <\/button>";
template += "                    <\/div>";
template += "                <\/div>";
template += "            <\/div>";
template += "        <\/div>";
template += "        <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
template += "            <div class=\"col-md-12 column\">";
template += "                <div class=\"panel panel-default\">";
template += "                    <div class=\"panel-heading\">";
template += "                        <h3 class=\"panel-title\">";
template += "                            Logs";
template += "                        <\/h3>";
template += "                    <\/div>";
template += "                    <div class=\"panel-body\">";
template += "                        <il ng-repeat=\"log in logs track by $index\"><span>{{log}}<\/span><\/il>";
template += "                    <\/div>";
template += "                <\/div>";
template += "            <\/div>";
template += "        <\/div>";
template += "    <\/div>";
template += "<\/div>";