var newEntryTemplate="";
newEntryTemplate += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
newEntryTemplate += "";
newEntryTemplate += "<div>";
newEntryTemplate += "    <div class=\"row clearfix\">";
newEntryTemplate += "        <div class=\"col-md-12 column\">";
newEntryTemplate += "            <b>HPI Encoder ver 1.0<\/b>";
newEntryTemplate += "        <\/div>";
newEntryTemplate += "    <\/div>";
newEntryTemplate += "    <div class=\"row clearfix\" ng-hide=\"isInputFieldsAreValid\">";
newEntryTemplate += "        <div class=\"col-md-12 column\">";
newEntryTemplate += "            WARNING : the input fields was change since the last update. Pls contact Mike to fix this. You know";
newEntryTemplate += "            where you can find me.";
newEntryTemplate += "        <\/div>";
newEntryTemplate += "    <\/div>";
newEntryTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
newEntryTemplate += "        <div class=\"col-md-12 column\">";
newEntryTemplate += "            <div class=\"panel panel-default\">";
newEntryTemplate += "                <div class=\"panel-heading\">";
newEntryTemplate += "                    <h3 class=\"panel-title\">";
newEntryTemplate += "                        Step 1 : Input the CSV to parse";
newEntryTemplate += "                    <\/h3>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "                <div class=\"panel-body\">";
newEntryTemplate += "                    <form role=\"form\">";
newEntryTemplate += "                        <div class=\"form-group\">";
newEntryTemplate += "                            <label for=\"csvText\">Paste CSV content here<\/label>";
newEntryTemplate += "                            <textarea class=\"form-control\" id=\"csvText\" ng-model=\"csvContent\"><\/textarea>";
newEntryTemplate += "                        <\/div>";
newEntryTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">Parse<\/button>";
newEntryTemplate += "                    <\/form>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "            <\/div>";
newEntryTemplate += "        <\/div>";
newEntryTemplate += "    <\/div>";
newEntryTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid && isNewEntry\">";
newEntryTemplate += "        <div class=\"col-md-12 column\">";
newEntryTemplate += "            <div class=\"panel panel-default\">";
newEntryTemplate += "                <div class=\"panel-heading\">";
newEntryTemplate += "                    <h3 class=\"panel-title\">";
newEntryTemplate += "                        Step 2 : Input user information";
newEntryTemplate += "                    <\/h3>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "                <div class=\"panel-body\">";
newEntryTemplate += "                    <form role=\"form\">";
newEntryTemplate += "                        <div class=\"form-group\" ng-show=\"isNewEntry\">";
newEntryTemplate += "                            <label for=\"uplineUserCode\">Your Upline User Code<\/label>";
newEntryTemplate += "                            <input type=\"text\" id=\"uplineUserCode\" class=\"form-control\"";
newEntryTemplate += "                                   placeholder=\"Your Upline User Code\" ng-model=\"uplineUserCode\"\/>";
newEntryTemplate += "                        <\/div>";
newEntryTemplate += "                        <div class=\"form-group\">";
newEntryTemplate += "                            <label for=\"firstName\">First Name<\/label>";
newEntryTemplate += "                            <input type=\"text\" id=\"firstName\" class=\"form-control\" placeholder=\"First Name\"";
newEntryTemplate += "                                   ng-model=\"firstName\"\/>";
newEntryTemplate += "                        <\/div>";
newEntryTemplate += "                        <div class=\"form-group\">";
newEntryTemplate += "                            <label for=\"middleName\">Middle Name<\/label>";
newEntryTemplate += "                            <input type=\"text\" id=\"middleName\" class=\"form-control\" placeholder=\"Middle Name\"";
newEntryTemplate += "                                   ng-model=\"middleName\"\/>";
newEntryTemplate += "                        <\/div>";
newEntryTemplate += "                        <div class=\"form-group\">";
newEntryTemplate += "                            <label for=\"lastName\">Last Name<\/label>";
newEntryTemplate += "                            <input type=\"text\" id=\"lastName\" class=\"form-control\" placeholder=\"Last Name\"";
newEntryTemplate += "                                   ng-model=\"lastName\"\/>";
newEntryTemplate += "                        <\/div>";
newEntryTemplate += "                        <div class=\"form-group\">";
newEntryTemplate += "                            <label for=\"userPassword\">User Password<\/label>";
newEntryTemplate += "                            <input type=\"text\" id=\"userPassword\" class=\"form-control\" placeholder=\"User Password\"";
newEntryTemplate += "                                   ng-model=\"password\"\/>";
newEntryTemplate += "                        <\/div>";
newEntryTemplate += "                    <\/form>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "            <\/div>";
newEntryTemplate += "        <\/div>";
newEntryTemplate += "    <\/div>";
newEntryTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
newEntryTemplate += "        <div class=\"col-md-12 column\">";
newEntryTemplate += "            <div class=\"panel panel-default\">";
newEntryTemplate += "                <div class=\"panel-heading\">";
newEntryTemplate += "                    <h3 class=\"panel-title\">";
newEntryTemplate += "                        Step 3 : Correct the fields below and click Encode.";
newEntryTemplate += "                    <\/h3>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "                <div class=\"panel-body\">";
newEntryTemplate += "                    <table class=\"table\">";
newEntryTemplate += "                        <thead>";
newEntryTemplate += "                        <tr>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                #";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                User Code";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                Referred By";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                Activation Code";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                Status";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                    <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
newEntryTemplate += "                                           ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Was Encoded";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                <input type=\"checkbox\" ng-model=\"enableEncodeOneItem\"";
newEntryTemplate += "                                              alt=\"Enable Encode One By One. By default this is disable to prevent accident.\"\/>";
newEntryTemplate += "                                Action";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                        <\/tr>";
newEntryTemplate += "                        <\/thead>";
newEntryTemplate += "                        <tbody>";
newEntryTemplate += "                        <tr ng-repeat=\"account in accounts\">";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                {{account.Index}}";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                <input type=\"input\" ng-model=\"account.UserCode\"\/>";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                <input type=\"input\" ng-model=\"account.ReferredBy\"\/>";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                <input type=\"input\" ng-model=\"account.ActivationCode\"";
newEntryTemplate += "                                       ng-change=\"ActivationCodeChange({{account.Index}})\"\/>";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                {{account.Status}}";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                <input type=\"checkbox\" ng-model=\"account.WasEncoded\"\/>";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                            <th>";
newEntryTemplate += "                                <button ng-click=\"EncodeOneItem(account.Index)\" ng-disabled=\"!isDone || !enableEncodeOneItem\">";
newEntryTemplate += "                                    Encode";
newEntryTemplate += "                                <\/button>";
newEntryTemplate += "                            <\/th>";
newEntryTemplate += "                        <\/tr>";
newEntryTemplate += "                        <\/tbody>";
newEntryTemplate += "                    <\/table>";
newEntryTemplate += "                    <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Encode()\" ng-disabled=\"!isDone\">Encode";
newEntryTemplate += "                        All";
newEntryTemplate += "                    <\/button>";
newEntryTemplate += "                    <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"StopEncoding()\">Stop";
newEntryTemplate += "                    <\/button>";
newEntryTemplate += "                    <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"encoded.csv\"";
newEntryTemplate += "                            csv-header=\"['User Code', 'Referred By', 'Activation Code']\">Export";
newEntryTemplate += "                    <\/button>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "            <\/div>";
newEntryTemplate += "        <\/div>";
newEntryTemplate += "    <\/div>";
newEntryTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
newEntryTemplate += "        <div class=\"col-md-12 column\">";
newEntryTemplate += "            <div class=\"panel panel-default\">";
newEntryTemplate += "                <div class=\"panel-heading\">";
newEntryTemplate += "                    <h3 class=\"panel-title\">";
newEntryTemplate += "                        Logs";
newEntryTemplate += "                    <\/h3>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "                <div class=\"panel-body\">";
newEntryTemplate += "                    <il ng-repeat=\"log in logs track by $index\"><span>{{log}}<\/span><\/il>";
newEntryTemplate += "                <\/div>";
newEntryTemplate += "            <\/div>";
newEntryTemplate += "        <\/div>";
newEntryTemplate += "    <\/div>";
newEntryTemplate += "<\/div>";
newEntryTemplate += "";
