var dashboardTemplate="";
dashboardTemplate += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
dashboardTemplate += "";
dashboardTemplate += "<div>";
dashboardTemplate += "    <div class=\"row clearfix\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <b>HPI Encoder ver {{version}}<\/b>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-hide=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            WARNING : the input fields were change since the last update. Pls contact Mike to fix this. You know";
dashboardTemplate += "            where you can find me.";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Step 1 : Input the CSV to parse";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <form role=\"form\">";
dashboardTemplate += "                        <div class=\"form-group\">";
dashboardTemplate += "                            <label for=\"csvText\">Paste CSV content here<\/label>";
dashboardTemplate += "                            <textarea class=\"form-control\" id=\"csvText\" ng-model=\"csvContent\"><\/textarea>";
dashboardTemplate += "                        <\/div>";
dashboardTemplate += "                        <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
dashboardTemplate += "                            <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">Parse<\/button>";
dashboardTemplate += "                            <button type=\"submit\" class=\"btn btn-default\" ng-click=\"csvContent=''\">Clear<\/button>";
dashboardTemplate += "                        <\/div>";
dashboardTemplate += "                        <span ng-show=\"parseMessage!=''\" class=\"text-danger\">{{parseMessage}}<\/span>";
dashboardTemplate += "                    <\/form>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Step 2 : User Dasboard";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Download()\" ng-disabled=\"!isDone\">";
dashboardTemplate += "                            Download All";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"Stop()\">Stop";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\"";
dashboardTemplate += "                                filename=\"dashboard.csv\"";
dashboardTemplate += "                                csv-header=\"['Username', 'TotalQB', 'Rebates', 'TotalProductVoucher','ActiveAccnt','NewEntry','ReadyRorEncashment','EncashmentHistory']\">";
dashboardTemplate += "                            Export";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
dashboardTemplate += "                               ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Skip?";
dashboardTemplate += "                    <\/div>";
dashboardTemplate += "                    <ul>";
dashboardTemplate += "                        <li ng-repeat=\"user in users\">";
dashboardTemplate += "                            <table class=\"table table-condensed\">";
dashboardTemplate += "                                <tbody>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>No<\/td>";
dashboardTemplate += "                                    <td>{{user.Index}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>User Name<\/td>";
dashboardTemplate += "                                    <td><input type=\"input\" ng-model=\"user.UserName\"\/><\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Password<\/td>";
dashboardTemplate += "                                    <td><input type=\"input\" ng-model=\"user.Password\"\/><\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>E-Wallet<\/td>";
dashboardTemplate += "                                    <td>{{user.Wallet}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Total QB<\/td>";
dashboardTemplate += "                                    <td>{{user.TotalQB}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Total Rebates<\/td>";
dashboardTemplate += "                                    <td>{{user.TotalRebates}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Total Product Voucher<\/td>";
dashboardTemplate += "                                    <td>{{user.TotalProductVoucher}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Active Accounts<\/td>";
dashboardTemplate += "                                    <td>{{user.ActiveAccnt}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>NewEntry Code<\/td>";
dashboardTemplate += "                                    <td>{{user.NewEntry}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Ready Ror Encashment<\/td>";
dashboardTemplate += "                                    <td ng-class=\"{info: user.HasBlue}\">{{user.ReadyRorEncashment}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Encashment History<\/td>";
dashboardTemplate += "                                    <td>{{user.EncashmentHistory}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Status<\/td>";
dashboardTemplate += "                                    <td ng-class=\"{danger: user.IsError, success: user.IsSuccess}\">{{user.Status}}<\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td>Skip?<\/td>";
dashboardTemplate += "                                    <td><input type=\"checkbox\" ng-model=\"user.WasDownloaded\"\/><\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <tr>";
dashboardTemplate += "                                    <td><\/td>";
dashboardTemplate += "                                    <td>";
dashboardTemplate += "                                        <button ng-click=\"LoginToDownloadOneItem(user)\" ng-disabled=\"!isDone\"";
dashboardTemplate += "                                                class=\"btn btn-default\">";
dashboardTemplate += "                                            {{user.DownloadBtn}}";
dashboardTemplate += "                                        <\/button>";
dashboardTemplate += "                                    <\/td>";
dashboardTemplate += "                                <\/tr>";
dashboardTemplate += "                                <\/tbody>";
dashboardTemplate += "                            <\/table>";
dashboardTemplate += "                        <\/li>";
dashboardTemplate += "                    <\/ul>";
dashboardTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Download()\" ng-disabled=\"!isDone\">";
dashboardTemplate += "                            Download All";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"Stop()\">Stop";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\"";
dashboardTemplate += "                                filename=\"dashboard.csv\"";
dashboardTemplate += "                                csv-header=\"['Username', 'TotalQB', 'Rebates', 'TotalProductVoucher','ActiveAccnt','NewEntry','ReadyRorEncashment','EncashmentHistory']\">";
dashboardTemplate += "                            Export";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
dashboardTemplate += "                               ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Skip?";
dashboardTemplate += "                    <\/div>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Logs";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <table>";
dashboardTemplate += "                        <tr ng-repeat=\"log in logs.slice().reverse() track by $index\">";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                {{log}}";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                        <\/tr>";
dashboardTemplate += "                    <\/table>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "<\/div>";
dashboardTemplate += "";
