var dashboardTemplate="";
dashboardTemplate += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
dashboardTemplate += "";
dashboardTemplate += "<div>";
dashboardTemplate += "    <div class=\"row clearfix\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <b>HPI Encoder ver {{version}}<\/b>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-hide=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            WARNING : the input fields were change since the last update. Pls contact Mike to fix this. You know";
dashboardTemplate += "            where you can find me.";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Step 1 : Input the CSV to parse";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <form role=\"form\">";
dashboardTemplate += "                        <div class=\"form-group\">";
dashboardTemplate += "                            <label for=\"csvText\">Paste CSV content here<\/label>";
dashboardTemplate += "                            <textarea class=\"form-control\" id=\"csvText\" ng-model=\"csvContent\"><\/textarea>";
dashboardTemplate += "                        <\/div>";
dashboardTemplate += "                        <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
dashboardTemplate += "                            <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">Parse<\/button>";
dashboardTemplate += "                            <button type=\"submit\" class=\"btn btn-default\" ng-click=\"csvContent=''\">Clear<\/button>";
dashboardTemplate += "                        <\/div>";
dashboardTemplate += "                        <span ng-show=\"parseMessage!=''\" class=\"text-danger\">{{parseMessage}}<\/span>";
dashboardTemplate += "                    <\/form>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Step 2 : User Dasboard";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Download()\" ng-disabled=\"!isDone\">Download All";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"Stop()\">Stop";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"dashboard.csv\"";
dashboardTemplate += "                                csv-header=\"['Username', 'TotalQB', 'Rebates', 'TotalProductVoucher','ActiveAccnt','NewEntry','ReadyRorEncashment','EncashmentHistory']\">Export";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
dashboardTemplate += "                               ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Skip?";
dashboardTemplate += "                    <\/div>";
dashboardTemplate += "                    <ul>";
dashboardTemplate += "                        <li ng-repeat=\"user in users\">";
dashboardTemplate += "                            <form class=\"form-horizontal\">";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">No<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        {{user.Index}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">User Name<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        <input type=\"input\" ng-model=\"user.UserName\"\/>";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Password<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        <input type=\"input\" ng-model=\"user.Password\"\/>";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Total QB<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        {{user.TotalQB}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Total Rebates<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        {{user.TotalRebates}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Total Product Voucher<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        {{user.TotalProductVoucher}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Active Accounts<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        {{user.ActiveAccnt}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">NewEntry Code<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        {{user.NewEntry}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Ready Ror Encashment<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\" ng-class=\"{info: user.HasBlue}\">";
dashboardTemplate += "                                        {{user.ReadyRorEncashment}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Encashment History<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\">";
dashboardTemplate += "                                        {{user.EncashmentHistory}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <label class=\"col-sm-2 control-label\">Status<\/label>";
dashboardTemplate += "                                    <div class=\"col-sm-10\" ng-class=\"{danger: user.IsError, success: user.IsSuccess}\">";
dashboardTemplate += "                                        {{user.Status}}";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <div class=\"col-sm-offset-2 col-sm-10\">";
dashboardTemplate += "                                        <input type=\"checkbox\" ng-model=\"user.WasDownloaded\"\/>";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                                <div class=\"form-group\">";
dashboardTemplate += "                                    <div class=\"col-sm-offset-2 col-sm-10\">";
dashboardTemplate += "                                        <button ng-click=\"LoginToDownloadOneItem(user)\" ng-disabled=\"!isDone\" class=\"btn btn-default\">";
dashboardTemplate += "                                            {{user.DownloadBtn}}";
dashboardTemplate += "                                        <\/button>";
dashboardTemplate += "                                    <\/div>";
dashboardTemplate += "                                <\/div>";
dashboardTemplate += "                            <\/form>";
dashboardTemplate += "                        <\/li>";
dashboardTemplate += "                    <\/ul>";
dashboardTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Download()\" ng-disabled=\"!isDone\">Download All";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"Stop()\">Stop";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"dashboard.csv\"";
dashboardTemplate += "                                csv-header=\"['Username', 'TotalQB', 'Rebates', 'TotalProductVoucher','ActiveAccnt','NewEntry','ReadyRorEncashment','EncashmentHistory']\">Export";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
dashboardTemplate += "                               ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Skip?";
dashboardTemplate += "                    <\/div>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Logs";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <table>";
dashboardTemplate += "                        <tr ng-repeat=\"log in logs.slice().reverse() track by $index\">";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                {{log}}";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                        <\/tr>";
dashboardTemplate += "                    <\/table>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "<\/div>";
dashboardTemplate += "";
