var reEntryTemplate="";
reEntryTemplate += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
reEntryTemplate += "";
reEntryTemplate += "<div>";
reEntryTemplate += "    <div class=\"row clearfix\">";
reEntryTemplate += "        <div class=\"col-md-12 column\">";
reEntryTemplate += "            <b>HPI Encoder ver {{version}}<\/b>";
reEntryTemplate += "        <\/div>";
reEntryTemplate += "    <\/div>";
reEntryTemplate += "    <div class=\"row clearfix\" ng-hide=\"isInputFieldsAreValid\">";
reEntryTemplate += "        <div class=\"col-md-12 column\">";
reEntryTemplate += "            WARNING : the input fields were change since the last update. Pls contact Mike to fix this. You know";
reEntryTemplate += "            where you can find me.";
reEntryTemplate += "        <\/div>";
reEntryTemplate += "    <\/div>";
reEntryTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
reEntryTemplate += "        <div class=\"col-md-12 column\">";
reEntryTemplate += "            <div class=\"panel panel-default\">";
reEntryTemplate += "                <div class=\"panel-heading\">";
reEntryTemplate += "                    <h3 class=\"panel-title\">";
reEntryTemplate += "                        Step 1 : Input the CSV to parse";
reEntryTemplate += "                    <\/h3>";
reEntryTemplate += "                <\/div>";
reEntryTemplate += "                <div class=\"panel-body\">";
reEntryTemplate += "                    <form role=\"form\">";
reEntryTemplate += "                        <div class=\"form-group\">";
reEntryTemplate += "                            <label for=\"csvText\">Paste CSV content here<\/label>";
reEntryTemplate += "                            <textarea class=\"form-control\" id=\"csvText\" ng-model=\"csvContent\"><\/textarea>";
reEntryTemplate += "                        <\/div>";
reEntryTemplate += "                        <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
reEntryTemplate += "                            <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">Parse<\/button>";
reEntryTemplate += "                            <button type=\"submit\" class=\"btn btn-default\" ng-click=\"csvContent=''\">Clear<\/button>";
reEntryTemplate += "                        <\/div>";
reEntryTemplate += "                        <span ng-show=\"parseMessage!=''\" class=\"text-danger\">{{parseMessage}}<\/span>";
reEntryTemplate += "                    <\/form>";
reEntryTemplate += "                <\/div>";
reEntryTemplate += "            <\/div>";
reEntryTemplate += "        <\/div>";
reEntryTemplate += "    <\/div>";
reEntryTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
reEntryTemplate += "        <div class=\"col-md-12 column\">";
reEntryTemplate += "            <div class=\"panel panel-default\">";
reEntryTemplate += "                <div class=\"panel-heading\">";
reEntryTemplate += "                    <h3 class=\"panel-title\">";
reEntryTemplate += "                        Step 2 : Correct the fields below and click Encode.";
reEntryTemplate += "                    <\/h3>";
reEntryTemplate += "                <\/div>";
reEntryTemplate += "                <div class=\"panel-body\">";
reEntryTemplate += "                    <p class=\"text-warning\">To enable encode one item, you must first check action checkbox. This is to avoid accidental click<\/p>";
reEntryTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
reEntryTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Encode()\" ng-disabled=\"!isDone\">Encode";
reEntryTemplate += "                            All";
reEntryTemplate += "                        <\/button>";
reEntryTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"StopEncoding()\">Stop";
reEntryTemplate += "                        <\/button>";
reEntryTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"encoded.csv\"";
reEntryTemplate += "                                csv-header=\"['User Code', 'Referred By', 'Activation Code']\">Export";
reEntryTemplate += "                        <\/button>";
reEntryTemplate += "                    <\/div>";
reEntryTemplate += "                    <table class=\"table\">";
reEntryTemplate += "                        <thead>";
reEntryTemplate += "                        <tr>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                #";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                User Code";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                Referred By";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                Activation Code";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                Status";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                    <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
reEntryTemplate += "                                           ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Was Encoded";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                <input type=\"checkbox\" ng-model=\"enableEncodeOneItem\"";
reEntryTemplate += "                                              alt=\"Enable Encode One By One. By default this is disable to prevent accident.\"\/>";
reEntryTemplate += "                                Action";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                        <\/tr>";
reEntryTemplate += "                        <\/thead>";
reEntryTemplate += "                        <tbody>";
reEntryTemplate += "                        <tr ng-repeat=\"account in accounts\">";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                {{account.Index}}";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                <input type=\"input\" ng-model=\"account.UserCode\"\/>";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                <input type=\"input\" ng-model=\"account.ReferredBy\"\/>";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                <input type=\"input\" ng-model=\"account.ActivationCode\"";
reEntryTemplate += "                                       ng-change=\"ActivationCodeChange(account)\"\/>";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                {{account.Status}}";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                <input type=\"checkbox\" ng-model=\"account.WasEncoded\"\/>";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                <button ng-click=\"EncodeOneItem(account)\" ng-disabled=\"!isDone || !enableEncodeOneItem\">";
reEntryTemplate += "                                    Encode";
reEntryTemplate += "                                <\/button>";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                        <\/tr>";
reEntryTemplate += "                        <\/tbody>";
reEntryTemplate += "                    <\/table>";
reEntryTemplate += "                    <p class=\"text-warning\">To enable encode one item, you must first check action checkbox. This is to avoid accidental click<\/p>";
reEntryTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
reEntryTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Encode()\" ng-disabled=\"!isDone\">Encode";
reEntryTemplate += "                            All";
reEntryTemplate += "                        <\/button>";
reEntryTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"StopEncoding()\">Stop";
reEntryTemplate += "                        <\/button>";
reEntryTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"encoded.csv\"";
reEntryTemplate += "                                csv-header=\"['User Code', 'Referred By', 'Activation Code']\">Export";
reEntryTemplate += "                        <\/button>";
reEntryTemplate += "                    <\/div>";
reEntryTemplate += "                <\/div>";
reEntryTemplate += "            <\/div>";
reEntryTemplate += "        <\/div>";
reEntryTemplate += "    <\/div>";
reEntryTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
reEntryTemplate += "        <div class=\"col-md-12 column\">";
reEntryTemplate += "            <div class=\"panel panel-default\">";
reEntryTemplate += "                <div class=\"panel-heading\">";
reEntryTemplate += "                    <h3 class=\"panel-title\">";
reEntryTemplate += "                        Logs";
reEntryTemplate += "                    <\/h3>";
reEntryTemplate += "                <\/div>";
reEntryTemplate += "                <div class=\"panel-body\">";
reEntryTemplate += "                    <table>";
reEntryTemplate += "                        <tr ng-repeat=\"log in logs.slice().reverse() track by $index\">";
reEntryTemplate += "                            <th>";
reEntryTemplate += "                                {{log}}";
reEntryTemplate += "                            <\/th>";
reEntryTemplate += "                        <\/tr>";
reEntryTemplate += "                    <\/table>";
reEntryTemplate += "                <\/div>";
reEntryTemplate += "            <\/div>";
reEntryTemplate += "        <\/div>";
reEntryTemplate += "    <\/div>";
reEntryTemplate += "<\/div>";
reEntryTemplate += "";
