var advanceCodeTemplate="";
advanceCodeTemplate += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
advanceCodeTemplate += "";
advanceCodeTemplate += "<div>";
advanceCodeTemplate += "    <div class=\"row clearfix\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <b>HPI Encoder ver 1.0<\/b>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-hide=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            WARNING : the input fields was change since the last update. Pls contact Mike to fix this. You know";
advanceCodeTemplate += "            where you can find me.";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <div class=\"panel panel-default\">";
advanceCodeTemplate += "                <div class=\"panel-heading\">";
advanceCodeTemplate += "                    <h3 class=\"panel-title\">";
advanceCodeTemplate += "                        Step 1 : Input the CSV to parse";
advanceCodeTemplate += "                    <\/h3>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "                <div class=\"panel-body\">";
advanceCodeTemplate += "                    <form role=\"form\">";
advanceCodeTemplate += "                        <div class=\"form-group\">";
advanceCodeTemplate += "                            <label for=\"csvText\">Paste CSV content here<\/label>";
advanceCodeTemplate += "                            <textarea class=\"form-control\" id=\"csvText\" ng-model=\"csvContent\"><\/textarea>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">Parse<\/button>";
advanceCodeTemplate += "                    <\/form>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "            <\/div>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid && isNewEntry\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <div class=\"panel panel-default\">";
advanceCodeTemplate += "                <div class=\"panel-heading\">";
advanceCodeTemplate += "                    <h3 class=\"panel-title\">";
advanceCodeTemplate += "                        Step 2 : Input user information";
advanceCodeTemplate += "                    <\/h3>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "                <div class=\"panel-body\">";
advanceCodeTemplate += "                    <form role=\"form\">";
advanceCodeTemplate += "                        <div class=\"form-group\" ng-show=\"isNewEntry\">";
advanceCodeTemplate += "                            <label for=\"uplineUserCode\">Your Upline User Code<\/label>";
advanceCodeTemplate += "                            <input type=\"text\" id=\"uplineUserCode\" class=\"form-control\"";
advanceCodeTemplate += "                                   placeholder=\"Your Upline User Code\" ng-model=\"uplineUserCode\"\/>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                        <div class=\"form-group\">";
advanceCodeTemplate += "                            <label for=\"firstName\">First Name<\/label>";
advanceCodeTemplate += "                            <input type=\"text\" id=\"firstName\" class=\"form-control\" placeholder=\"First Name\"";
advanceCodeTemplate += "                                   ng-model=\"firstName\"\/>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                        <div class=\"form-group\">";
advanceCodeTemplate += "                            <label for=\"middleName\">Middle Name<\/label>";
advanceCodeTemplate += "                            <input type=\"text\" id=\"middleName\" class=\"form-control\" placeholder=\"Middle Name\"";
advanceCodeTemplate += "                                   ng-model=\"middleName\"\/>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                        <div class=\"form-group\">";
advanceCodeTemplate += "                            <label for=\"lastName\">Last Name<\/label>";
advanceCodeTemplate += "                            <input type=\"text\" id=\"lastName\" class=\"form-control\" placeholder=\"Last Name\"";
advanceCodeTemplate += "                                   ng-model=\"lastName\"\/>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                        <div class=\"form-group\">";
advanceCodeTemplate += "                            <label for=\"userPassword\">User Password<\/label>";
advanceCodeTemplate += "                            <input type=\"text\" id=\"userPassword\" class=\"form-control\" placeholder=\"User Password\"";
advanceCodeTemplate += "                                   ng-model=\"password\"\/>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                    <\/form>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "            <\/div>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <div class=\"panel panel-default\">";
advanceCodeTemplate += "                <div class=\"panel-heading\">";
advanceCodeTemplate += "                    <h3 class=\"panel-title\">";
advanceCodeTemplate += "                        Step 3 : Correct the fields below and click Encode.";
advanceCodeTemplate += "                    <\/h3>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "                <div class=\"panel-body\">";
advanceCodeTemplate += "                    <table class=\"table\">";
advanceCodeTemplate += "                        <thead>";
advanceCodeTemplate += "                        <tr>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                #";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                User Code";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                Referred By";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                Activation Code";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                Status";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                    <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
advanceCodeTemplate += "                                           ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Was Encoded";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"checkbox\" ng-model=\"enableEncodeOneItem\"";
advanceCodeTemplate += "                                              alt=\"Enable Encode One By One. By default this is disable to prevent accident.\"\/>";
advanceCodeTemplate += "                                Action";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                        <\/tr>";
advanceCodeTemplate += "                        <\/thead>";
advanceCodeTemplate += "                        <tbody>";
advanceCodeTemplate += "                        <tr ng-repeat=\"account in accounts\">";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                {{account.Index}}";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"input\" ng-model=\"account.UserCode\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"input\" ng-model=\"account.ReferredBy\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"input\" ng-model=\"account.ActivationCode\"";
advanceCodeTemplate += "                                       ng-change=\"ActivationCodeChange({{account.Index}})\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                {{account.Status}}";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"checkbox\" ng-model=\"account.WasEncoded\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <button ng-click=\"EncodeOneItem(account.Index)\" ng-disabled=\"!isDone || !enableEncodeOneItem\">";
advanceCodeTemplate += "                                    Encode";
advanceCodeTemplate += "                                <\/button>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                        <\/tr>";
advanceCodeTemplate += "                        <\/tbody>";
advanceCodeTemplate += "                    <\/table>";
advanceCodeTemplate += "                    <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Encode()\" ng-disabled=\"!isDone\">Encode";
advanceCodeTemplate += "                        All";
advanceCodeTemplate += "                    <\/button>";
advanceCodeTemplate += "                    <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"StopEncoding()\">Stop";
advanceCodeTemplate += "                    <\/button>";
advanceCodeTemplate += "                    <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"encoded.csv\"";
advanceCodeTemplate += "                            csv-header=\"['User Code', 'Referred By', 'Activation Code']\">Export";
advanceCodeTemplate += "                    <\/button>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "            <\/div>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <div class=\"panel panel-default\">";
advanceCodeTemplate += "                <div class=\"panel-heading\">";
advanceCodeTemplate += "                    <h3 class=\"panel-title\">";
advanceCodeTemplate += "                        Logs";
advanceCodeTemplate += "                    <\/h3>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "                <div class=\"panel-body\">";
advanceCodeTemplate += "                    <il ng-repeat=\"log in logs track by $index\"><span>{{log}}<\/span><\/il>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "            <\/div>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "<\/div>";
advanceCodeTemplate += "";
