var advanceCodeTemplate="";
advanceCodeTemplate += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
advanceCodeTemplate += "";
advanceCodeTemplate += "<div>";
advanceCodeTemplate += "    <div class=\"row clearfix\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <b>HPI Encoder ver {{version}}<\/b>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-hide=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            WARNING : the input fields were change since the last update. Pls contact Mike to fix this. You know";
advanceCodeTemplate += "            where you can find me.";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <div class=\"panel panel-default\">";
advanceCodeTemplate += "                <div class=\"panel-heading\">";
advanceCodeTemplate += "                    <h3 class=\"panel-title\">";
advanceCodeTemplate += "                        Step 1 : Input the CSV to parse";
advanceCodeTemplate += "                    <\/h3>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "                <div class=\"panel-body\">";
advanceCodeTemplate += "                    <form role=\"form\">";
advanceCodeTemplate += "                        <div class=\"form-group\">";
advanceCodeTemplate += "                            <label for=\"csvText\">Paste CSV content here<\/label>";
advanceCodeTemplate += "                            <textarea class=\"form-control\" id=\"csvText\" ng-model=\"csvContent\"><\/textarea>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                        <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
advanceCodeTemplate += "                            <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">Parse<\/button>";
advanceCodeTemplate += "                            <button type=\"submit\" class=\"btn btn-default\" ng-click=\"csvContent=''\">Clear<\/button>";
advanceCodeTemplate += "                        <\/div>";
advanceCodeTemplate += "                        <span ng-show=\"parseMessage!=''\" class=\"text-danger\">{{parseMessage}}<\/span>";
advanceCodeTemplate += "                    <\/form>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "            <\/div>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <div class=\"panel panel-default\">";
advanceCodeTemplate += "                <div class=\"panel-heading\">";
advanceCodeTemplate += "                    <h3 class=\"panel-title\">";
advanceCodeTemplate += "                        Step 2 : Correct the fields below and click Encode.";
advanceCodeTemplate += "                    <\/h3>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "                <div class=\"panel-body\">";
advanceCodeTemplate += "                    <p class=\"text-warning\">To enable encode one item, you must first check action checkbox. This is to avoid accidental click<\/p>";
advanceCodeTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
advanceCodeTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Encode()\" ng-disabled=\"!isDone\">Encode";
advanceCodeTemplate += "                            All";
advanceCodeTemplate += "                        <\/button>";
advanceCodeTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"StopEncoding()\">Stop";
advanceCodeTemplate += "                        <\/button>";
advanceCodeTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"encoded.csv\"";
advanceCodeTemplate += "                                csv-header=\"['User Code', 'Referred By', 'Activation Code']\">Export";
advanceCodeTemplate += "                        <\/button>";
advanceCodeTemplate += "                    <\/div>";
advanceCodeTemplate += "                    <table class=\"table\">";
advanceCodeTemplate += "                        <thead>";
advanceCodeTemplate += "                        <tr>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                #";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                User Code";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                Referred By";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                Activation Code";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                Status";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                    <input type=\"checkbox\" ng-change=\"selectAllFn(selectAll)\"";
advanceCodeTemplate += "                                           ng-checked=\"isSelectedAll()\" ng-model=\"selectAll\"\/> Was Encoded";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"checkbox\" ng-model=\"enableEncodeOneItem\"";
advanceCodeTemplate += "                                              alt=\"Enable Encode One By One. By default this is disable to prevent accident.\"\/>";
advanceCodeTemplate += "                                Action";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                        <\/tr>";
advanceCodeTemplate += "                        <\/thead>";
advanceCodeTemplate += "                        <tbody>";
advanceCodeTemplate += "                        <tr ng-repeat=\"account in accounts\" ng-class=\"{danger: account.IsError, success: account.IsSuccess}\">";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                {{account.Index}}";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"input\" ng-model=\"account.UserCode\" maxlength=\"20\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"input\" ng-model=\"account.ReferredBy\" maxlength=\"20\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"input\" ng-model=\"account.ActivationCode\"";
advanceCodeTemplate += "                                       ng-change=\"ActivationCodeChange(account)\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                {{account.Status}}";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <input type=\"checkbox\" ng-model=\"account.WasEncoded\"\/>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                <button ng-click=\"EncodeOneItem(account)\">";
advanceCodeTemplate += "                                    {{account.EncodeBtn}}";
advanceCodeTemplate += "                                <\/button>";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                        <\/tr>";
advanceCodeTemplate += "                        <\/tbody>";
advanceCodeTemplate += "                    <\/table>";
advanceCodeTemplate += "                    <p class=\"text-warning\">To enable encode one item, you must first check action checkbox. This is to avoid accidental click<\/p>";
advanceCodeTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
advanceCodeTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Encode()\" ng-disabled=\"!isDone\">Encode";
advanceCodeTemplate += "                            All";
advanceCodeTemplate += "                        <\/button>";
advanceCodeTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"StopEncoding()\">Stop";
advanceCodeTemplate += "                        <\/button>";
advanceCodeTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\" filename=\"encoded.csv\"";
advanceCodeTemplate += "                                csv-header=\"['User Code', 'Referred By', 'Activation Code']\">Export";
advanceCodeTemplate += "                        <\/button>";
advanceCodeTemplate += "                    <\/div>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "            <\/div>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
advanceCodeTemplate += "        <div class=\"col-md-12 column\">";
advanceCodeTemplate += "            <div class=\"panel panel-default\">";
advanceCodeTemplate += "                <div class=\"panel-heading\">";
advanceCodeTemplate += "                    <h3 class=\"panel-title\">";
advanceCodeTemplate += "                        Logs";
advanceCodeTemplate += "                    <\/h3>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "                <div class=\"panel-body\">";
advanceCodeTemplate += "                    <table>";
advanceCodeTemplate += "                        <tr ng-repeat=\"log in logs.slice().reverse() track by $index\">";
advanceCodeTemplate += "                            <th>";
advanceCodeTemplate += "                                {{log}}";
advanceCodeTemplate += "                            <\/th>";
advanceCodeTemplate += "                        <\/tr>";
advanceCodeTemplate += "                    <\/table>";
advanceCodeTemplate += "                <\/div>";
advanceCodeTemplate += "            <\/div>";
advanceCodeTemplate += "        <\/div>";
advanceCodeTemplate += "    <\/div>";
advanceCodeTemplate += "<\/div>";
advanceCodeTemplate += "";